## DEFINE NAME
name: Demon Github Actions Workflow

## DEFINE EXECUTION POLICY
on: 
  push:
    branches: [ 'main', 'dev' ]

## DEFINE ENVIRONMENT

## DEFINE JOB(S)
jobs:

  ## JOB: SOURCE CODE ANALYSIS
  SourceCode:

    ## DEFINE RUNNER
    runs-on: ubuntu-latest

    ## DEFINE PERMISSIONS

    ## DEFINE STEPS
    steps:

      ## STEP: EXAMPLE LINT
      - name: Linting
        run: echo This is a dummy Linting Step