## DEFINE NAME
name: Demo Github Actions Workflow

## DEFINE EXECUTION POLICY
on: 
  push:
    branches: [ 'main', 'dev' ]

  ## ALLOW MANUAL DEPLOYMENT
  workflow-dispatch:

## DEFINE ENVIRONMENT

## DEFINE JOB(S)
jobs:

  ## JOB: LINTING
  Linting:

    ## DEFINE JOB
    runs-on: ubuntu-latest

    ## DEFINE PERMISSIONS

    ## DEFINE STEPS
    steps:

      ## STEP: EXAMPLE LINT
      - name: Linting
        run: echo This is a dummy Linting Step

  ## JOB: SECRET DETECTION
  SecretDetection:

    ## DEFINE JOB
    runs-on: ubuntu-latest

    ## DEFINE PERMISSIONS

    ## DEFINE STEPS
    steps:
  
      ## STEP: EXAMPLE SECRET DETECTION
      - name: Secret Detection
        run: echo This is a dummy Secret Detection Step

  ## JOB: LINTING
  SAST:

    ## DEFINE JOB
    runs-on: ubuntu-latest

    ## DEFINE PERMISSIONS

    ## DEFINE STEPS
    steps:

      ## STEP: EXAMPLE SAST
      - name: SAST
        run: echo This is a dummy SAST Step

  ## JOB: BUILD
  Build:

    ## DEFINE JOB
    runs-on: ubuntu-latest
    needs: [ 'Linting', 'SecretDetection', 'SAST' ]

    ## DEFINE PERMISSIONS

    ## DEFINE STEPS
    steps:

      ## STEP: EXAMPLE BUILD
      - name: Build
        run: echo This is a dummy Build Step

  ## JOB: CONTAINER SECURITY
  ContainerSecurityScan:

    ## DEFINE JOB
    runs-on: ubuntu-latest
    needs: [ 'Build' ]

    ## DEFINE PERMISSIONS

    ## DEFINE STEPS
    steps:

      ## STEP: EXAMPLE CSS
      - name: CSS
        run: echo This is a dummy CSS Step

  ## JOB: SBOM
  SBOM:

    ## DEFINE JOB
    runs-on: ubuntu-latest
    needs: [ 'Build' ]

    ## DEFINE PERMISSIONS

    ## DEFINE STEPS
    steps:

      ## STEP: EXAMPLE SBOM
      - name: SBOM
        run: echo This is a dummy SBOM Step

  ## JOB: DAST
  DAST:

    ## DEFINE JOB
    runs-on: ubuntu-latest
    needs: [ 'Build' ]

    ## DEFINE PERMISSIONS

    ## DEFINE STEPS
    steps:

      ## STEP: EXAMPLE DAST
      - name: DAST
        run: echo This is a dummy DAST Step